# Generated by Django 5.2.8 on 2025-12-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Badge name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Badge description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "progress_badge",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChildBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        help_text="Badge that was awarded",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awarded_to",
                        to="progress.badge",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        help_text="Child who earned the badge",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="badges",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "progress_childbadge",
                "ordering": ["-awarded_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "awarded_at"],
                        name="progress_ch_child_i_42d4b4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "badge"), name="unique_child_badge"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not-started", "Not Started"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not-started",
                        help_text="Current completion status",
                        max_length=20,
                    ),
                ),
                (
                    "points_earned",
                    models.IntegerField(
                        default=0, help_text="Points earned from this lesson"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time child accessed this lesson",
                        null=True,
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, help_text="When lesson was completed", null=True
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        help_text="Child's progress",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress",
                        to="profiles.childprofile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Lesson being tracked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "progress_progress",
                "indexes": [
                    models.Index(
                        fields=["child", "last_accessed"],
                        name="progress_pr_child_i_c0dc71_idx",
                    ),
                    models.Index(
                        fields=["status", "completion_date"],
                        name="progress_pr_status_5d133f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "lesson"), name="unique_child_lesson_progress"
                    )
                ],
            },
        ),
    ]
