# Generated by Django 5.2.8 on 2025-12-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="childprofile",
            new_name="profiles_ch_uuid_a4fa53_idx",
            old_name="accounts_ch_uuid_5663c5_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_email_74c8d6_idx",
            old_name="profiles_us_email_e41b23_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_role_1fa9a5_idx",
            old_name="profiles_us_role_7e41dc_idx",
        ),
        migrations.AlterModelTable(
            name="childprofile",
            table="profiles_childprofile",
        ),
        migrations.AlterModelTable(
            name="teacherprofile",
            table="profiles_teacherprofile",
        ),
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
    ]
