# Generated by Django 5.2.8 on 2025-12-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0002_rename_accounts_ch_uuid_5663c5_idx_profiles_ch_uuid_a4fa53_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="profiles_us_email_e41b23_idx",
            old_name="accounts_us_email_74c8d6_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="profiles_us_role_7e41dc_idx",
            old_name="accounts_us_role_1fa9a5_idx",
        ),
        migrations.AlterModelTable(
            name="user",
            table="profiles_user",
        ),
    ]
