# Generated by Django 5.2.8 on 2025-12-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_rename_accounts_us_email_74c8d6_idx_profiles_us_email_e41b23_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_email_74c8d6_idx",
            old_name="profiles_us_email_e41b23_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_role_1fa9a5_idx",
            old_name="profiles_us_role_7e41dc_idx",
        ),
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
    ]
