# Generated by Django 6.0.1 on 2026-01-16 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0005_rename_accounts_us_email_74c8d6_idx_profiles_us_email_e41b23_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="childprofile",
            options={"ordering": ["id"]},
        ),
    ]
