# Generated by Django 5.2.8 on 2025-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="The category of action (e.g., 'LOGIN_SUCCESS', 'PASSWORD_CHANGE').",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the object being modified (e.g., ML_MODEL_ID).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed payload (IP address, Browser agent, old vs new values).",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The exact moment the action was recorded.",
                    ),
                ),
            ],
            options={
                "db_table": "core_auditlog",
                "ordering": ["-created_at"],
            },
        ),
    ]
