# Generated by Django 6.0 on 2025-12-31 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "profiles",
            "0005_rename_accounts_us_email_74c8d6_idx_profiles_us_email_e41b23_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRealtimeAggregate",
            fields=[
                (
                    "ml_student_id",
                    models.IntegerField(
                        help_text="ML team's internal student ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "avg_time_spent",
                    models.FloatField(
                        default=0.0, help_text="Average time spent per lesson (minutes)"
                    ),
                ),
                (
                    "avg_video_watch",
                    models.FloatField(
                        default=0.0, help_text="Average video watch percentage (0-100)"
                    ),
                ),
                (
                    "avg_clicks",
                    models.FloatField(
                        default=0.0, help_text="Average number of clicks per lesson"
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Lesson completion rate (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "avg_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Average quiz score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "avg_wrong_questions",
                    models.FloatField(
                        default=0.0, help_text="Average wrong questions per quiz"
                    ),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        default=0.0,
                        help_text="Average response time per question (seconds)",
                    ),
                ),
                (
                    "avg_attempt_number",
                    models.FloatField(
                        default=0.0, help_text="Average attempt number per quiz"
                    ),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(
                        default=0, help_text="Number of lessons completed"
                    ),
                ),
                (
                    "badges_earned",
                    models.IntegerField(default=0, help_text="Number of badges earned"),
                ),
                (
                    "streak_days",
                    models.IntegerField(
                        default=0, help_text="Current login streak in days"
                    ),
                ),
                (
                    "topic_mastery",
                    models.FloatField(
                        default=0.0, help_text="Topic mastery score (0-100)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update timestamp for the aggregate row",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        help_text="Django ChildProfile reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_student_realtime_aggregate",
                "indexes": [
                    models.Index(
                        fields=["ml_student_id"], name="ml_student__ml_stud_be87b6_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="ml_student__updated_6bc565_idx"
                    ),
                ],
            },
        ),
    ]
