"""
Shared models for both Offline and Online ML pipelines.
"""

import uuid

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from profiles.models import ChildProfile


# ==============================================================================
# 1. ML MODEL METADATA
# ==============================================================================

class MLModel(models.Model):
    """Metadata for AI model versions and artifact locations."""

    name = models.CharField(
        max_length=100,
        help_text="Model name"
    )
    version = models.CharField(
        max_length=50,
        help_text="Model version"
    )
    file_path = models.CharField(
        max_length=500,
        help_text="Artifact location"
    )
    metadata = models.JSONField(
        null=True,
        blank=True,
        help_text="Model metadata"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ml_mlmodel"
        constraints = [
            models.UniqueConstraint(
                fields=["name", "version"],
                name="unique_model_version"
            )
        ]
        indexes = [
            models.Index(fields=["name", "version"]),
            models.Index(fields=["created_at"])
        ]

    def __str__(self):
        return f"{self.name} v{self.version}"


# ==============================================================================
# 2. STUDENT MAPPING
# ==============================================================================

class MLStudentMap(models.Model):
    """Bridge table mapping ML internal IDs to backend ChildProfiles."""

    ml_student_id = models.IntegerField(
        primary_key=True,
        help_text="ML team's internal student ID"
    )
    student_uuid = models.UUIDField(
        null=True,
        blank=True,
        db_index=True,
        help_text="UUID from User model"
    )
    child = models.ForeignKey(
        ChildProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="ml_mappings"
    )
    mapped_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ml_mlstudentmap"
        indexes = [
            models.Index(fields=["student_uuid"]),
            models.Index(fields=["child"]),
            models.Index(fields=["mapped_at"])
        ]

    def save(self, *args, **kwargs):
        """Populate student_uuid from related User or generate a new one."""
        if not self.student_uuid:
            if self.child and getattr(self.child, "user", None):
                user_uuid = getattr(self.child.user, "uuid", None)
                self.student_uuid = user_uuid or uuid.uuid4()
            else:
                self.student_uuid = uuid.uuid4()
        super().save(*args, **kwargs)

    def __str__(self):
        if self.child and hasattr(self.child, "user"):
            return f"ML{self.ml_student_id} -> {self.child.user.username}"
        return f"ML{self.ml_student_id} -> No mapping"


# ==============================================================================
# 3. BASE INTERACTION MODEL
# ==============================================================================

class BaseInteractionModel(models.Model):
    """Abstract base to keep ML student fields consistent."""

    ml_student_id = models.IntegerField(
        help_text="ML team's internal student ID"
    )
    student_uuid = models.CharField(
        max_length=36,
        null=True,
        blank=True,
        help_text="UUID from accounts.User"
    )
    child = models.ForeignKey(
        ChildProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+"
    )

    class Meta:
        abstract = True


# ==============================================================================
# 4. RECOMMENDATIONS
# ==============================================================================

class Recommendation(models.Model):
    """Actionable insights generated by the AI for the user."""

    child = models.ForeignKey(
        ChildProfile,
        on_delete=models.PROTECT,
        related_name="recommendations"
    )
    lesson = models.ForeignKey(
        "lessons.Lesson",
        on_delete=models.PROTECT,
        related_name="recommendations"
    )
    confidence_score = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(1)]
    )
    reason = models.TextField(null=True, blank=True)
    model = models.ForeignKey(
        MLModel,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="recommendations"
    )
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ml_recommendation"
        ordering = ["-confidence_score"]
        indexes = [
            models.Index(fields=["child", "-confidence_score"]),
            models.Index(fields=["generated_at"])
        ]

    def __str__(self):
        child_name = self.child.user.username if self.child and self.child.user else "Unknown"
        return (
            f"Recommendation {self.id}: {self.lesson.title} "
            f"for {child_name} (confidence: {self.confidence_score:.2f})"
        )
