# Generated by Django 6.0 on 2025-12-31 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "profiles",
            "0005_rename_accounts_us_email_74c8d6_idx_profiles_us_email_e41b23_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "avg_time_spent",
                    models.FloatField(help_text="Average time spent per lesson"),
                ),
                (
                    "avg_video_watch",
                    models.FloatField(help_text="Average video watch percentage"),
                ),
                (
                    "avg_clicks",
                    models.FloatField(help_text="Average clicks per lesson"),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        help_text="Lesson completion rate (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_lesson_features",
                "indexes": [
                    models.Index(
                        fields=["computed_at"], name="ml_lesson_f_compute_10450d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonInteractionsClean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(
                        help_text="Lesson ID from lessons_lesson table"
                    ),
                ),
                (
                    "time_spent",
                    models.FloatField(
                        help_text="Clipped time spent (1-30 minutes)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "video_watch_percentage",
                    models.FloatField(
                        help_text="Clipped video watch percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "number_of_clicks",
                    models.IntegerField(
                        help_text="Number of clicks (>=0)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "completion_status",
                    models.BooleanField(help_text="Completion status"),
                ),
                ("cleaned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_lesson_interactions_clean",
                "indexes": [
                    models.Index(
                        fields=["child", "lesson_id"],
                        name="ml_lesson_i_child_i_c657ae_idx",
                    ),
                    models.Index(
                        fields=["cleaned_at"], name="ml_lesson_i_cleaned_6bdd05_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonInteractionsRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(
                        help_text="Lesson ID from lessons_lesson table"
                    ),
                ),
                (
                    "time_spent",
                    models.FloatField(help_text="Time spent on lesson (minutes)"),
                ),
                (
                    "video_watch_percentage",
                    models.FloatField(
                        help_text="Raw video watch percentage (0-150)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "number_of_clicks",
                    models.IntegerField(help_text="Number of clicks/interactions"),
                ),
                (
                    "completion_status",
                    models.BooleanField(help_text="Whether lesson was completed"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_lesson_interactions_raw",
                "indexes": [
                    models.Index(
                        fields=["ml_student_id", "received_at"],
                        name="ml_lesson_i_ml_stud_62fb7f_idx",
                    ),
                    models.Index(
                        fields=["lesson_id", "received_at"],
                        name="ml_lesson_i_lesson__72e5bd_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="ml_lesson_i_receive_abc0f2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgressClean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(
                        help_text="Validated lesson count",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "badges_earned",
                    models.IntegerField(
                        help_text="Badges clipped to max system limit (0-12)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "streak_days",
                    models.IntegerField(
                        help_text="Login streak clipped (0-50)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "topic_mastery",
                    models.FloatField(
                        help_text="Mastery score normalized (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("cleaned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_progress_clean",
                "indexes": [
                    models.Index(
                        fields=["cleaned_at"], name="ml_progress_cleaned_45948a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgressLabeled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(help_text="Number of lessons completed"),
                ),
                (
                    "badges_earned",
                    models.IntegerField(help_text="Number of badges earned"),
                ),
                ("streak_days", models.IntegerField(help_text="Current streak")),
                (
                    "topic_mastery",
                    models.FloatField(help_text="Topic mastery score (0-100)"),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        help_text="Mastery level classification",
                        max_length=10,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_progress_labeled",
                "indexes": [
                    models.Index(
                        fields=["mastery_level", "computed_at"],
                        name="ml_progress_mastery_6757f1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgressRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(help_text="Lessons completed today"),
                ),
                ("badges_earned", models.IntegerField(help_text="Badges earned today")),
                ("streak_days", models.IntegerField(help_text="Current login streak")),
                (
                    "topic_mastery",
                    models.FloatField(help_text="Raw topic mastery score"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_progress_raw",
                "indexes": [
                    models.Index(
                        fields=["ml_student_id", "received_at"],
                        name="ml_progress_ml_stud_2687f7_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="ml_progress_receive_a07515_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuizAttemptsClean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(
                        help_text="Lesson ID from lessons_lesson table"
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        help_text="Attempt number clipped (max 3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Normalized score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "wrong_questions",
                    models.IntegerField(
                        help_text="Validated wrong questions (0-4)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        help_text="Response time clipped (5-150s)",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                ("cleaned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_quiz_attempts_clean",
                "indexes": [
                    models.Index(
                        fields=["child", "lesson_id"],
                        name="ml_quiz_att_child_i_56bf3f_idx",
                    ),
                    models.Index(
                        fields=["cleaned_at"], name="ml_quiz_att_cleaned_2871cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuizAttemptsRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(help_text="Lesson ID linked to this quiz"),
                ),
                (
                    "attempt_number",
                    models.IntegerField(help_text="Attempt number (1st, 2nd, etc.)"),
                ),
                ("score", models.FloatField(help_text="Raw numerical score")),
                (
                    "wrong_questions",
                    models.IntegerField(help_text="Count of incorrect answers"),
                ),
                ("response_time", models.FloatField(help_text="Total time in seconds")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_quiz_attempts_raw",
                "indexes": [
                    models.Index(
                        fields=["ml_student_id", "lesson_id"],
                        name="ml_quiz_att_ml_stud_5784fc_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="ml_quiz_att_receive_07d42a_idx"
                    ),
                    models.Index(
                        fields=["lesson_id", "attempt_number"],
                        name="ml_quiz_att_lesson__161688_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuizFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "avg_score",
                    models.FloatField(
                        help_text="Average quiz score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "avg_wrong_questions",
                    models.FloatField(help_text="Average wrong questions per quiz"),
                ),
                (
                    "avg_response_time",
                    models.FloatField(help_text="Average response time per quiz"),
                ),
                (
                    "avg_attempt_number",
                    models.FloatField(help_text="Average attempt number per quiz"),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_quiz_features",
                "indexes": [
                    models.Index(
                        fields=["computed_at"], name="ml_quiz_fea_compute_01614a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentMLDataset",
            fields=[
                (
                    "student_id",
                    models.IntegerField(
                        help_text="ML internal student ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avg_time_spent",
                    models.FloatField(help_text="Average time spent per lesson"),
                ),
                (
                    "avg_video_watch",
                    models.FloatField(help_text="Average video watch percentage"),
                ),
                (
                    "avg_clicks",
                    models.FloatField(help_text="Average clicks per lesson"),
                ),
                (
                    "completion_rate",
                    models.FloatField(help_text="Lesson completion rate (0-1)"),
                ),
                ("avg_score", models.FloatField(help_text="Average quiz score")),
                (
                    "avg_wrong_questions",
                    models.FloatField(help_text="Average wrong questions"),
                ),
                (
                    "avg_response_time",
                    models.FloatField(help_text="Average response time"),
                ),
                (
                    "avg_attempt_number",
                    models.FloatField(help_text="Average attempt number"),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(help_text="Lessons completed"),
                ),
                ("badges_earned", models.IntegerField(help_text="Badges earned")),
                ("streak_days", models.IntegerField(help_text="Current streak days")),
                (
                    "topic_mastery",
                    models.FloatField(help_text="Topic mastery score (0-100)"),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        help_text="Target classification",
                        max_length=10,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        auto_now_add=True, help_text="Snapshot creation date"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        help_text="Backend Child reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_student_ml_dataset",
                "indexes": [
                    models.Index(
                        fields=["snapshot_date"], name="ml_student__snapsho_90d3f3_idx"
                    ),
                    models.Index(
                        fields=["mastery_level"], name="ml_student__mastery_4700f0_idx"
                    ),
                ],
            },
        ),
    ]
