# Generated by Django 5.2.8 on 2025-12-28 12:26

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "time_limit_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional time limit in seconds",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(30)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quizzes",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table": "quizzes_quiz",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                ("media_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "options",
                    models.JSONField(default=list, help_text="List of answer choices"),
                ),
                (
                    "correct_option_index",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "quizzes_question",
                "ordering": ["order"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("correct_option_index__gte", 0)),
                        name="correct_option_index_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=list)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("correct_count", models.PositiveSmallIntegerField(default=0)),
                ("total_questions", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_attempts",
                        to="profiles.childprofile",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "quizzes_quizattempt",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "created_at"],
                        name="quizzes_qui_child_i_9c99ba_idx",
                    ),
                    models.Index(
                        fields=["quiz", "created_at"],
                        name="quizzes_qui_quiz_id_ee15fc_idx",
                    ),
                ],
            },
        ),
    ]
