# Generated by Django 6.0.1 on 2026-01-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0008_mediaupload_file_alter_mediaupload_file_type_and_more"),
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="lessons.lesson",
            ),
        ),
    ]
