# Generated by Django 6.0.1 on 2026-01-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0008_mediaupload_file_alter_mediaupload_file_type_and_more"),
        ("quizzes", "0002_alter_question_question_text_alter_quiz_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quizzes",
                to="lessons.lesson",
            ),
            preserve_default=False,
        ),
    ]
