# Generated by Django 6.0 on 2025-12-31 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lessons", "0007_alter_collection_slug"),
        (
            "profiles",
            "0005_rename_accounts_us_email_74c8d6_idx_profiles_us_email_e41b23_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Model name", max_length=100)),
                ("version", models.CharField(help_text="Model version", max_length=50)),
                (
                    "file_path",
                    models.CharField(help_text="Artifact location", max_length=500),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, help_text="Model metadata", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_mlmodel",
                "indexes": [
                    models.Index(
                        fields=["name", "version"], name="ml_mlmodel_name_1e7a19_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ml_mlmodel_created_d9edbf_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="unique_model_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MLStudentMap",
            fields=[
                (
                    "ml_student_id",
                    models.IntegerField(
                        help_text="ML team's internal student ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID from User model",
                        null=True,
                    ),
                ),
                ("mapped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_mappings",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ml_mlstudentmap",
                "indexes": [
                    models.Index(
                        fields=["student_uuid"], name="ml_mlstuden_student_1f938d_idx"
                    ),
                    models.Index(
                        fields=["child"], name="ml_mlstuden_child_i_6cac55_idx"
                    ),
                    models.Index(
                        fields=["mapped_at"], name="ml_mlstuden_mapped__d07ab7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="profiles.childprofile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="ai.mlmodel",
                    ),
                ),
            ],
            options={
                "db_table": "ml_recommendation",
                "ordering": ["-confidence_score"],
                "indexes": [
                    models.Index(
                        fields=["child", "-confidence_score"],
                        name="ml_recommen_child_i_864419_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="ml_recommen_generat_4d629b_idx"
                    ),
                ],
            },
        ),
    ]
