# Generated by Django 5.2.8 on 2025-12-28 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "avg_time_spent",
                    models.FloatField(
                        help_text="Average time spent per lesson (minutes)"
                    ),
                ),
                (
                    "avg_video_watch",
                    models.FloatField(
                        help_text="Average video watch percentage (0-100)"
                    ),
                ),
                (
                    "avg_clicks",
                    models.FloatField(help_text="Average number of clicks per lesson"),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        help_text="Lesson completion rate (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_lesson_features",
            },
        ),
        migrations.CreateModel(
            name="LessonInteractionsClean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(
                        help_text="Lesson ID from lessons_lesson table"
                    ),
                ),
                (
                    "time_spent",
                    models.FloatField(
                        help_text="Clipped time spent (1-30 minutes)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "video_watch_percentage",
                    models.FloatField(
                        help_text="Clipped watch percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "number_of_clicks",
                    models.IntegerField(
                        help_text="Number of clicks (>=0)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "completion_status",
                    models.BooleanField(help_text="Completion status"),
                ),
                ("cleaned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_lesson_interactions_clean",
            },
        ),
        migrations.CreateModel(
            name="LessonInteractionsRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(
                        help_text="Lesson ID from lessons_lesson table"
                    ),
                ),
                (
                    "time_spent",
                    models.FloatField(help_text="Time spent on lesson (minutes)"),
                ),
                (
                    "video_watch_percentage",
                    models.FloatField(
                        help_text="Raw video watch percentage (0-150)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "number_of_clicks",
                    models.IntegerField(help_text="Number of clicks/interactions"),
                ),
                (
                    "completion_status",
                    models.BooleanField(help_text="Whether lesson was completed"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_lesson_interactions_raw",
            },
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Model name", max_length=100)),
                ("version", models.CharField(help_text="Model version", max_length=50)),
                (
                    "file_path",
                    models.CharField(help_text="Artifact location", max_length=500),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, help_text="Model metadata", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_mlmodel",
            },
        ),
        migrations.CreateModel(
            name="MLStudentMap",
            fields=[
                (
                    "ml_student_id",
                    models.IntegerField(
                        help_text="ML team's internal student ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from User model (accounts.User.uuid)",
                        max_length=36,
                        null=True,
                    ),
                ),
                ("mapped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_mlstudentmap",
            },
        ),
        migrations.CreateModel(
            name="ProgressClean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(
                        help_text="Validated non-negative lesson count",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "badges_earned",
                    models.IntegerField(
                        help_text="Badges clipped to max system limit (0-12)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "streak_days",
                    models.IntegerField(
                        help_text="Streak clipped to a yearly limit (0-50)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "topic_mastery",
                    models.FloatField(
                        help_text="Mastery score normalized (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cleaned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the raw data was sanitized"
                    ),
                ),
            ],
            options={
                "db_table": "ml_progress_clean",
            },
        ),
        migrations.CreateModel(
            name="ProgressLabeled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(help_text="Number of lessons completed"),
                ),
                (
                    "badges_earned",
                    models.IntegerField(help_text="Number of badges earned"),
                ),
                (
                    "streak_days",
                    models.IntegerField(help_text="Current streak in days"),
                ),
                (
                    "topic_mastery",
                    models.FloatField(help_text="Topic mastery score (0-100)"),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        help_text="Mastery level classification",
                        max_length=10,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_progress_labeled",
            },
        ),
        migrations.CreateModel(
            name="ProgressRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(
                        help_text="Total lessons finished recorded today"
                    ),
                ),
                (
                    "badges_earned",
                    models.IntegerField(
                        help_text="Total badges unlocked recorded today"
                    ),
                ),
                (
                    "streak_days",
                    models.IntegerField(help_text="Current login streak in days"),
                ),
                (
                    "topic_mastery",
                    models.FloatField(help_text="Raw mastery score (unclipped)"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of log entry"
                    ),
                ),
            ],
            options={
                "db_table": "ml_progress_raw",
            },
        ),
        migrations.CreateModel(
            name="QuizAttemptsClean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(
                        help_text="Lesson ID from lessons_lesson table"
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        help_text="Attempt count clipped (max 3 for statistical use)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Score normalized to 0-100 range",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "wrong_questions",
                    models.IntegerField(
                        help_text="Validated count (0-4)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        help_text="Response time clipped (5s to 150s)",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "cleaned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of sanitization"
                    ),
                ),
            ],
            options={
                "db_table": "ml_quiz_attempts_clean",
            },
        ),
        migrations.CreateModel(
            name="QuizAttemptsRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(help_text="Lesson ID linked to this quiz"),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        help_text="Ordinal attempt count (1st, 2nd, etc.)"
                    ),
                ),
                ("score", models.FloatField(help_text="Raw numerical score achieved")),
                (
                    "wrong_questions",
                    models.IntegerField(help_text="Count of incorrect answers"),
                ),
                (
                    "response_time",
                    models.FloatField(help_text="Total time taken in seconds"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_quiz_attempts_raw",
            },
        ),
        migrations.CreateModel(
            name="QuizFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_student_id",
                    models.IntegerField(help_text="ML team's internal student ID"),
                ),
                (
                    "student_uuid",
                    models.CharField(
                        blank=True,
                        help_text="UUID from accounts.User",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "avg_score",
                    models.FloatField(
                        help_text="Average quiz score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "avg_wrong_questions",
                    models.FloatField(help_text="Average wrong questions per quiz"),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        help_text="Average response time per question (seconds)"
                    ),
                ),
                (
                    "avg_attempt_number",
                    models.FloatField(help_text="Average attempt number per quiz"),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_quiz_features",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="AI confidence (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why this was recommended", null=True
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ml_recommendation",
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.CreateModel(
            name="StudentMLDataset",
            fields=[
                (
                    "student_id",
                    models.IntegerField(
                        help_text="ML Internal Student ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avg_time_spent",
                    models.FloatField(
                        help_text="Average time spent per lesson (minutes)"
                    ),
                ),
                (
                    "avg_video_watch",
                    models.FloatField(
                        help_text="Average video watch percentage (0-100)"
                    ),
                ),
                (
                    "avg_clicks",
                    models.FloatField(help_text="Average number of clicks per lesson"),
                ),
                (
                    "completion_rate",
                    models.FloatField(help_text="Lesson completion rate (0-1)"),
                ),
                (
                    "avg_score",
                    models.FloatField(help_text="Average quiz score (0-100)"),
                ),
                (
                    "avg_wrong_questions",
                    models.FloatField(help_text="Average wrong questions per quiz"),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        help_text="Average response time per question (seconds)"
                    ),
                ),
                (
                    "avg_attempt_number",
                    models.FloatField(help_text="Average attempt number per quiz"),
                ),
                (
                    "lessons_completed",
                    models.IntegerField(help_text="Number of lessons completed"),
                ),
                (
                    "badges_earned",
                    models.IntegerField(help_text="Number of badges earned"),
                ),
                (
                    "streak_days",
                    models.IntegerField(help_text="Current streak in days"),
                ),
                (
                    "topic_mastery",
                    models.FloatField(help_text="Topic mastery score (0-100)"),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        help_text="Target classification",
                        max_length=10,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date of snapshot creation"
                    ),
                ),
            ],
            options={
                "db_table": "ml_student_ml_dataset",
            },
        ),
    ]
