# Generated by Django 5.2.8 on 2025-12-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("lessons", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonfeatures",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="lessoninteractionsclean",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="lessoninteractionsraw",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["name", "version"], name="ml_mlmodel_name_1e7a19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["created_at"], name="ml_mlmodel_created_d9edbf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mlmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_model_version"
            ),
        ),
        migrations.AddField(
            model_name="mlstudentmap",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ml_mappings",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="progressclean",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="progresslabeled",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="progressraw",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="quizattemptsclean",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="quizattemptsraw",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="quizfeatures",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Django ChildProfile reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="child",
            field=models.ForeignKey(
                help_text="Target child",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommendations",
                to="profiles.childprofile",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="lesson",
            field=models.ForeignKey(
                help_text="Recommended lesson",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommendations",
                to="lessons.lesson",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="model",
            field=models.ForeignKey(
                blank=True,
                help_text="Model used for prediction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="ai.mlmodel",
            ),
        ),
        migrations.AddField(
            model_name="studentmldataset",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Backend Child Reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.childprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonfeatures",
            index=models.Index(
                fields=["computed_at"], name="ml_lesson_f_compute_10450d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessoninteractionsclean",
            index=models.Index(
                fields=["child", "lesson_id"], name="ml_lesson_i_child_i_c657ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessoninteractionsclean",
            index=models.Index(
                fields=["cleaned_at"], name="ml_lesson_i_cleaned_6bdd05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessoninteractionsraw",
            index=models.Index(
                fields=["ml_student_id", "received_at"],
                name="ml_lesson_i_ml_stud_62fb7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessoninteractionsraw",
            index=models.Index(
                fields=["lesson_id", "received_at"],
                name="ml_lesson_i_lesson__72e5bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessoninteractionsraw",
            index=models.Index(
                fields=["received_at"], name="ml_lesson_i_receive_abc0f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlstudentmap",
            index=models.Index(
                fields=["student_uuid"], name="ml_mlstuden_student_1f938d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlstudentmap",
            index=models.Index(fields=["child"], name="ml_mlstuden_child_i_6cac55_idx"),
        ),
        migrations.AddIndex(
            model_name="mlstudentmap",
            index=models.Index(
                fields=["mapped_at"], name="ml_mlstuden_mapped__d07ab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progressclean",
            index=models.Index(
                fields=["cleaned_at"], name="ml_progress_cleaned_45948a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progresslabeled",
            index=models.Index(
                fields=["mastery_level", "computed_at"],
                name="ml_progress_mastery_6757f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="progressraw",
            index=models.Index(
                fields=["ml_student_id", "received_at"],
                name="ml_progress_ml_stud_2687f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="progressraw",
            index=models.Index(
                fields=["received_at"], name="ml_progress_receive_a07515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattemptsclean",
            index=models.Index(
                fields=["child", "lesson_id"], name="ml_quiz_att_child_i_56bf3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattemptsclean",
            index=models.Index(
                fields=["cleaned_at"], name="ml_quiz_att_cleaned_2871cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattemptsraw",
            index=models.Index(
                fields=["ml_student_id", "lesson_id"],
                name="ml_quiz_att_ml_stud_5784fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizattemptsraw",
            index=models.Index(
                fields=["received_at"], name="ml_quiz_att_receive_07d42a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattemptsraw",
            index=models.Index(
                fields=["lesson_id", "attempt_number"],
                name="ml_quiz_att_lesson__161688_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizfeatures",
            index=models.Index(
                fields=["computed_at"], name="ml_quiz_fea_compute_01614a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["child", "-confidence_score"],
                name="ml_recommen_child_i_864419_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["generated_at"], name="ml_recommen_generat_4d629b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmldataset",
            index=models.Index(
                fields=["snapshot_date"], name="ml_student__snapsho_90d3f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmldataset",
            index=models.Index(
                fields=["mastery_level"], name="ml_student__mastery_4700f0_idx"
            ),
        ),
    ]
