# Generated by Django 5.2.8 on 2025-12-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlstudentmap",
            name="student_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID from User model (accounts.User.uuid)",
                null=True,
            ),
        ),
    ]
