# Generated by Django 5.2.8 on 2025-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Lesson title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed lesson description"),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="S3/CDN URL for video content", max_length=500
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for lesson thumbnail",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="Lesson duration in seconds", null=True
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        help_text="Lesson difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether lesson is publicly available"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lessons_lesson",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(help_text="URL of uploaded file", max_length=500),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("video/mp4", "MP4 Video"),
                            ("video/webm", "WebM Video"),
                            ("image/png", "PNG Image"),
                            ("image/jpg", "JPG Image"),
                        ],
                        help_text="MIME type of the file",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lessons_mediaupload",
            },
        ),
    ]
