# Generated by Django 5.2.8 on 2025-12-28 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher who created the lesson",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="profiles.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="mediaupload",
            name="uploader",
            field=models.ForeignKey(
                help_text="User who uploaded the file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["slug"], name="lessons_les_slug_ebe546_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["difficulty"], name="lessons_les_difficu_afc96e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="lessons_les_is_publ_5c0844_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaupload",
            index=models.Index(
                fields=["status", "created_at"], name="lessons_med_status_f46ac9_idx"
            ),
        ),
    ]
