# Generated by Django 5.2.8 on 2025-12-29 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="lessons_les_slug_ebe546_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="lessons_les_difficu_afc96e_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="lessons_les_is_publ_5c0844_idx",
        ),
        migrations.AlterModelTable(
            name="lesson",
            table=None,
        ),
    ]
