# Generated by Django 5.2.8 on 2025-12-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_alter_lesson_options_and_more"),
        (
            "profiles",
            "0005_rename_accounts_us_email_74c8d6_idx_profiles_us_email_e41b23_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["slug"], name="lessons_les_slug_ebe546_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["difficulty"], name="lessons_les_difficu_afc96e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="lessons_les_is_publ_5c0844_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="lesson",
            table="lessons_lesson",
        ),
    ]
