# Generated by Django 5.2.8 on 2025-12-29 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaupload",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_uploads",
                to="lessons.lesson",
            ),
            preserve_default=False,
        ),
    ]
