# Generated by Django 5.2.8 on 2025-12-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0006_collection_lesson_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
