# Generated by Django 6.0.1 on 2026-01-17 20:18

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0007_alter_collection_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaupload",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="The actual video/image/audio file being uploaded",
                null=True,
                upload_to=lessons.models.get_media_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="mediaupload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("video/mp4", "MP4 Video"),
                    ("video/webm", "WebM Video"),
                    ("image/png", "PNG Image"),
                    ("image/jpg", "JPG Image"),
                    ("audio/mpeg", "MP3 Audio"),
                ],
                help_text="MIME type of the file",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mediaupload",
            name="file_url",
            field=models.URLField(
                blank=True, help_text="S3/CDN URL if applicable", max_length=500
            ),
        ),
    ]
