# Generated by Django 6.0.1 on 2026-01-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0008_mediaupload_file_alter_mediaupload_file_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="lesson",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for lesson",
                null=True,
                upload_to="media/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Uploaded video file",
                null=True,
                upload_to="media/video/",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: External URL if not uploading file",
                max_length=500,
            ),
        ),
    ]
