# Generated by Django 6.0.1 on 2026-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0009_remove_lesson_thumbnail_url_lesson_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for lesson",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Uploaded video file",
                null=True,
                upload_to="video/",
            ),
        ),
    ]
