# Generated by Django 6.0.1 on 2026-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_alter_lesson_thumbnail_alter_lesson_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Uploaded video file",
                null=True,
                upload_to="videos/",
            ),
        ),
    ]
